POST http://localhost:5000/api/groups
Content-Type: application/json

{
  "name": "2222",
  "password": "2222",
  "isPublic": true,
  "introduction": "두두번째 데이터입니다다"
}

#####
GET http://localhost:5000/api/groups?page=1&pageSize=5&sortBy=latest

#####
GET http://localhost:5000/api/groups

####
GET http://localhost:5000/api/groups?keyword=test group
####
GET http://localhost:5000/api/groups?isPublic=false
####


PUT http://localhost:5000/api/groups/1
Content-Type: application/json

{
  "name": "여러번 바꾼 이름",
  "password": "1234",
  "isPublic": false,
  "introduction": "UpUpUpdated introduction"
}
####

DELETE http://localhost:5000/api/groups/1
Content-Type: application/json

{
  "password": "kkkk"
}



###게시글1
POST http://localhost:5000/api/groups/1/posts
Content-Type:application/json

{
  "nickname": "닉네임임",
	"title": "게시글1",
	"content": "게시글1내용",
	"postPassword": "게시글1비번",
	"groupPassword": "1234",
	"imageUrl": "string",
	"tags": [ "태그1", "태그2" ],
	"location": "위치",
	"moment": "2024-02-21",
	"isPublic": true
}
####
POST http://localhost:5000/api/posts/1/comments
Content-Type: application/json

{
  "nickname": "민정",
  "content": "우와 멋져요!",
  "password": "민정"
}

####
GET http://localhost:5000/api/posts/1/comments?page=1&pageSize=10


####
PUT http://localhost:5000/api/comments/2
Content-Type: application/json

{
  "nickname": "은정",
  "content": "유익한 내용이네요~",
  "password": "은정"
}


###
DELETE http://localhost:5000/api/comments/1
Content-Type: application/json

{
  "password": "은정"
}
